# Generated by Django 5.2.17 on 2026-10-04 01:37

import appPrincipal.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_barra', models.CharField(max_length=20, verbose_name='Código de Barra')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, default='', null=True, verbose_name='Descripción')),
                ('imagen_principal', models.ImageField(default='', upload_to='productos/', verbose_name='Imagen Principal')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Opcional 2')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Opcional 3')),
                ('imagen_4', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Opcional 4')),
                ('imagen_5', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Opcional 5')),
                ('imagen_6', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Opcional 6')),
                ('categoria', models.CharField(choices=[('VIDEOJUEGOS', [('Videojuegos PS3', 'PlayStation 3'), ('Videojuegos PS4', 'PlayStation 4'), ('Videojuegos PS5', 'PlayStation 5'), ('Videojuegos XBOX 360', 'Xbox 360'), ('Videojuegos XBOX ONE', 'Xbox One'), ('Videojuegos XBOX SERIES', 'Xbox Series'), ('Videojuegos Nintendo 3DS', 'Nintendo 3DS'), ('Videojuegos WII', 'Nintendo Wii'), ('Videojuegos WII U', 'Nintendo Wii U'), ('Videojuegos Nintendo SWITCH', 'Nintendo Switch'), ('Videojuegos para PC', 'PC')]), ('CONSOLAS', [('Ps4 Consolas', 'Consola PlayStation 4'), ('Ps5 Consolas', 'Consola PlayStation 5'), ('Xbox One Consolas', 'Consola Xbox One'), ('Xbox Series Consolas', 'Consola Xbox Series'), ('Wii U Consolas', 'Consola Wii U'), ('Switch Consolas', 'Consola Switch')]), ('ACCESORIOS', [('Accesorios Psp', 'PSP'), ('Accesorios Ps Vita', 'PlayStation Vita'), ('Accesorios PS1', 'PlayStation 1'), ('Accesorios PS2', 'PlayStation 2'), ('Accesorios PS3', 'PlayStation 3'), ('Accesorios PS4', 'PlayStation 4'), ('Accesorios PS5', 'PlayStation 5'), ('Accesorios XBOX 360', 'Xbox 360'), ('Accesorios XBOX ONE', 'Xbox One'), ('Accesorios XBOX SERIES', 'Xbox Series'), ('Accesorios Nintendo 3DS', 'Nintendo 3DS'), ('Accesorios WII U', 'Wii U'), ('Accesorios Nintendo SWITCH', 'Switch')]), ('FIGURAS', [('Figuras Funko', 'Funko Pop'), ('Figuras Amiibo', 'Amiibo')])], max_length=40, verbose_name='Categoría')),
                ('genero', models.CharField(choices=[('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('RPG', 'RPG'), ('DEPORTES', 'Deportes'), ('CARRERAS', 'Carreras'), ('ESTRATEGIA', 'Estrategia'), ('SIMULACION', 'Simulación'), ('PUZZLE', 'Puzzle'), ('TERROR', 'Terror'), ('CONSOLAS', 'Consolas'), ('FIGURAS', 'Figuras'), ('ACCESORIOS', 'Accesorios'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Género')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=120, verbose_name='Dirección')),
                ('region', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', appPrincipal.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appPrincipal.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio', models.PositiveIntegerField(default=0)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('metodo_pago', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(choices=[('Sin Enviar', 'Sin Enviar'), ('Enviado', 'Enviado')], default='Sin Enviar', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_envio', models.CharField(choices=[('domicilio', 'Envío a domicilio'), ('tienda', 'Retiro en tienda')], default='', max_length=10)),
                ('direccion_envio', models.TextField(blank=True, null=True)),
                ('carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.carrito')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Respondido', 'Respondido')], default='Abierto', max_length=20)),
                ('asunto', models.CharField(default='No especificado', max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('respuesta', models.TextField(blank=True, null=True, verbose_name='Respuesta del administrador')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos', to='appPrincipal.venta')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_venta', to='appPrincipal.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_seguimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_preparacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_transito', models.DateTimeField(blank=True, null=True)),
                ('fecha_reparto', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('En Preparación', 'En Preparación'), ('Enviado', 'Enviado'), ('En Tránsito', 'En Tránsito'), ('En Reparto', 'En Reparto'), ('Entregado', 'Entregado'), ('Anulada', 'Anulada')], default='En Preparación', max_length=20)),
                ('transportista', models.CharField(default='Starken', max_length=50)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_envio', to='appPrincipal.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(verbose_name='Motivo de la devolución')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='devoluciones/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='devoluciones/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='devoluciones/')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('respuesta_admin', models.TextField(blank=True, null=True, verbose_name='Respuesta del administrador')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.producto')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='appPrincipal.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='boletas/')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='appPrincipal.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('puntuacion', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Puntuación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='appPrincipal.producto')),
            ],
            options={
                'verbose_name': 'Opinión',
                'verbose_name_plural': 'Opiniones',
                'unique_together': {('usuario', 'producto')},
            },
        ),
    ]
