# Generated by Django 5.2.17 on 2026-10-04 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='estado',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appPrincipal.producto'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='appPrincipal.venta'),
        ),
        migrations.AlterField(
            model_name='productoventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appPrincipal.producto'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamos', to='appPrincipal.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'producto'), name='favorito_unico'),
        ),
        migrations.AddConstraint(
            model_name='itemcarritoproducto',
            constraint=models.UniqueConstraint(fields=('carrito', 'producto'), name='item_carrito_unico'),
        ),
    ]
