# Generated by Django 4.2.11 on 2025-11-29 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0002_usuario_es_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_seguimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('En Preparación', 'En Preparación'), ('Enviado', 'Enviado'), ('En Tránsito', 'En Tránsito'), ('Entregado', 'Entregado')], default='En Preparación', max_length=20)),
                ('transportista', models.CharField(default='Starken', max_length=50)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_envio', to='appPrincipal.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(verbose_name='Motivo de la devolución')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('respuesta_admin', models.TextField(blank=True, null=True, verbose_name='Respuesta del administrador')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.usuario')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='appPrincipal.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='boletas/')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='appPrincipal.venta')),
            ],
        ),
    ]
