# Generated by Django 5.2.17 on 2026-10-04 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0002_rediseno_historial_y_restricciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('carrusel', 'Carrusel del menú'), ('lanzamientos', 'Nuevos lanzamientos (home)'), ('menu_videojuegos', 'Navbar: menú Videojuegos'), ('menu_consolas', 'Navbar: menú Consolas'), ('menu_accesorios', 'Navbar: menú Accesorios'), ('menu_figuras', 'Navbar: menú Figuras')], max_length=20, verbose_name='Sección')),
                ('titulo', models.CharField(max_length=80, verbose_name='Título')),
                ('texto', models.TextField(blank=True, max_length=400)),
                ('imagen', models.ImageField(blank=True, help_text='Opcional: si no se sube, se usa la imagen del producto.', null=True, upload_to='destacados/')),
                ('etiqueta', models.CharField(blank=True, help_text='Texto corto sobre la imagen, ej: ¡NUEVO!', max_length=20)),
                ('video_url', models.URLField(blank=True, help_text='Solo para nuevos lanzamientos. Ej: https://www.youtube.com/watch?v=...', verbose_name='Video de YouTube')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Los números menores se muestran primero.')),
                ('activo', models.BooleanField(default=True, help_text='Si se desactiva, deja de mostrarse en el sitio.')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appPrincipal.producto')),
            ],
            options={
                'ordering': ['seccion', 'orden', 'id'],
            },
        ),
    ]
