# Generated by Django 4.2.11 on 2025-12-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0003_envio_devolucion_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
