# Generated by Django 5.2.17 on 2026-10-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0004_portada_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='datos_navegacion_autorizados_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Autorizó el uso de datos de navegación'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='privacidad_aceptada_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aceptó la política de privacidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='privacidad_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='Versión de la política aceptada'),
        ),
    ]
