# Generated by Django 4.2.11 on 2025-12-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0005_producto_deleted_at_producto_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='fecha_entrega',
            new_name='fecha_entregado',
        ),
        migrations.AddField(
            model_name='envio',
            name='fecha_preparacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='fecha_reparto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='fecha_transito',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('En Preparación', 'En Preparación'), ('Enviado', 'Enviado'), ('En Tránsito', 'En Tránsito'), ('En Reparto', 'En Reparto'), ('Entregado', 'Entregado')], default='En Preparación', max_length=20),
        ),
    ]
