# Generated by Django 5.2.17 on 2026-10-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0005_consentimientos_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_envio',
            field=models.CharField(choices=[('tienda', 'Retiro en tienda'), ('delivery', 'Delivery Express en Valdivia'), ('bluexpress', 'Envío a región por Bluexpress'), ('por_pagar', 'Envío por pagar'), ('domicilio', 'Envío a domicilio')], default='', max_length=10),
        ),
    ]
