# Generated by Django 5.2.17 on 2026-10-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0006_opciones_de_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='fecha_listo_retiro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Listo para retiro desde'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('En Preparación', 'En Preparación'), ('Enviado', 'Enviado'), ('En Tránsito', 'En Tránsito'), ('En Reparto', 'En Reparto'), ('Listo para retiro', 'Listo para retiro'), ('Entregado', 'Entregado'), ('Anulada', 'Anulada')], default='En Preparación', max_length=20),
        ),
    ]
