# Generated by Django 4.2.11 on 2025-12-04 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0006_rename_fecha_entrega_envio_fecha_entregado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='fecha_entregado',
            new_name='fecha_entrega',
        ),
    ]
