# Generated by Django 5.2.17 on 2026-10-06 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0007_listo_para_retiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoWebpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_compra', models.CharField(max_length=26, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('monto', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado por el cliente'), ('reembolsado', 'Reembolsado (sin stock)'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('detalle', models.CharField(blank=True, help_text='Motivo del estado, para el cliente y el panel.', max_length=255)),
                ('items', models.JSONField()),
                ('metodo_envio', models.CharField(choices=[('tienda', 'Retiro en tienda'), ('delivery', 'Delivery Express en Valdivia'), ('bluexpress', 'Envío a región por Bluexpress'), ('por_pagar', 'Envío por pagar'), ('domicilio', 'Envío a domicilio')], max_length=10)),
                ('direccion_envio', models.TextField(blank=True)),
                ('codigo_autorizacion', models.CharField(blank=True, max_length=10)),
                ('tipo_pago', models.CharField(blank=True, max_length=2)),
                ('cuotas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tarjeta_ultimos_digitos', models.CharField(blank=True, max_length=4)),
                ('fecha_transaccion', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.JSONField(blank=True, help_text='Respuesta completa de Transbank (auditoría).', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_webpay', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago_webpay', to='appPrincipal.venta')),
            ],
            options={
                'verbose_name': 'Pago Webpay',
                'verbose_name_plural': 'Pagos Webpay',
                'ordering': ['-creado'],
            },
        ),
    ]
