# Generated by Django 4.2.11 on 2025-12-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0007_rename_fecha_entregado_envio_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_de_barra',
            field=models.CharField(max_length=20, verbose_name='Código de Barra'),
        ),
    ]
