# Generated by Django 4.2.11 on 2025-12-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0008_alter_producto_codigo_de_barra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('En Preparación', 'En Preparación'), ('Enviado', 'Enviado'), ('En Tránsito', 'En Tránsito'), ('En Reparto', 'En Reparto'), ('Entregado', 'Entregado'), ('Anulada', 'Anulada')], default='En Preparación', max_length=20),
        ),
    ]
