# Generated by Django 4.2.11 on 2025-12-05 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0009_alter_envio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos', to='appPrincipal.venta'),
        ),
    ]
