# Generated by Django 4.2.11 on 2025-12-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0010_reclamo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
