# Generated by Django 4.2.11 on 2025-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0011_devolucion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='devoluciones/'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='devoluciones/'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='devoluciones/'),
        ),
    ]
