# Generated by Django 4.2.11 on 2025-12-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0012_devolucion_imagen1_devolucion_imagen2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta'),
        ),
    ]
