"""
Django settings for Akaispace project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from django.contrib.messages import constants as messages
from decouple import config, Csv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Se define en el archivo .env (ver .env.example). Es obligatoria.
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'axes',
    'appPrincipal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # debe ir al final: bloquea el login tras varios intentos fallidos
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'Akaispace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'appPrincipal.context_processors.usuario_context',
                'appPrincipal.context_processors.portada_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Akaispace.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='db_akaispace'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {'user_attributes': ('email', 'nombre')},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        # complejidad (RNF-01): al menos una letra y un número
        'NAME': 'appPrincipal.seguridad.LetraYNumeroValidator',
    },
]


# Autenticación
AUTH_USER_MODEL = 'appPrincipal.Usuario'

AUTHENTICATION_BACKENDS = [
    # django-axes debe ir primero para poder bloquear los intentos
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = 'login'

# Límite de intentos de login (django-axes): tras 5 intentos fallidos con el mismo
# correo desde la misma IP, se bloquea por 15 minutos.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]
AXES_RESET_ON_SUCCESS = True
AXES_USERNAME_CALLABLE = 'appPrincipal.seguridad.email_para_axes'
AXES_LOCKOUT_CALLABLE = 'appPrincipal.seguridad.login_bloqueado'


# Webpay Plus de Transbank (HU-05). Ver appPrincipal/webpay.py.
# En 'integracion' se usan las credenciales públicas de prueba que trae el SDK de Transbank;
# en 'produccion' son obligatorios el código de comercio y la API key entregados por Transbank.
WEBPAY_AMBIENTE = config('WEBPAY_AMBIENTE', default='integracion')
WEBPAY_CODIGO_COMERCIO = config('WEBPAY_CODIGO_COMERCIO', default='')
WEBPAY_API_KEY = config('WEBPAY_API_KEY', default='')
# segundos máximos de espera a Transbank (el SDK trae 600 por defecto)
WEBPAY_TIMEOUT = config('WEBPAY_TIMEOUT', default=30, cast=int)


# Correo: confirmación de compra (HU-06) y recuperación de contraseña (HU-11). Ver appPrincipal/correos.py.
# Por defecto los correos se muestran en la consola de runserver (no se envían de verdad);
# para enviarlos, en el .env se usa el backend SMTP con los datos de la cuenta (ver .env.example).
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
# segundos máximos de espera al servidor de correo (sin esto, un SMTP caído deja colgada la página)
EMAIL_TIMEOUT = 10
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Akaispace <akaispacevaldivia@gmail.com>')
# dirección pública del sitio, para los enlaces de los correos que no salen de una petición (ej: la boleta)
SITIO_URL = config('SITIO_URL', default='http://localhost:8000').rstrip('/')
# el enlace para recuperar la contraseña vence en 1 hora (HU-11)
PASSWORD_RESET_TIMEOUT = 60 * 60


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# Carpeta donde `collectstatic` reúne los archivos estáticos al desplegar.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}

# Configuración de las sesiones
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  
SESSION_COOKIE_AGE = 3600  
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  
SESSION_SAVE_EVERY_REQUEST = True 

# Logging: los mensajes de appPrincipal se muestran en la consola.
# En desarrollo (DEBUG=True) se ven desde nivel DEBUG; en producción desde INFO.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '[{asctime}] {levelname} {name}: {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
    },
    'loggers': {
        'appPrincipal': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
    },
}
